spring:
  application:
    name: pnc-parcial-final-restaurante

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurante_final_db
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 1234567890123456789012345678901234567890123456789012345678901234
  access-expiration: 900000
  refresh-expiration: 604800000

server:
  port: 8080